# Camera type
camera_type: picam

# Database paths
embeddings_db: face_embeddings.db
mappings_db: face_mappings.db

# Display dataset path
animation_dirs: [images/collages, images/averages]

# Should the images be saved to disk, or stored in memory only?
# NOTE: if True, then enabling a write-only SD card will fail!
save_images_to_disk: False

# Collage parameters
min_num_faces_in_collage: 1
max_num_faces_in_collage: 8
num_frames_in_collage_animation: 50

# Image processing parameters
blur_threshold: 180 # Definitely check on this - depends on camera (50 - 200)
min_width: 150
margin_fraction: 0.6 # This might need to be wider. NOTE: source of bugs!
height_output: 1920 # Should be same as monitor height :`wlr-randr`
width_output: 1080 # Should be same as monitor width: `wlr-randr`

# Margins of final output image. NOTE: highly dependent on `margin_fraction`
l: 1.5
r: 1.5
t: 2.0
b: 2.5

# Dataset parameters
face_memory: 6 # How many faces before the same is allowed again?
tolerance: 0.6 # Face recognition tolerance.

# Other parameters
triangulation_indexes: None # This should be changed to a pre-computer path.
debug_images: False
