# Database paths
embeddings_db: face_embeddings.db"
mappings_db: face_mappings.db"

# Collage parameters
min_num_faces_in_collage: 2
max_num_faces_in_collage: 6
num_frames_in_collage_animation: 50

# Image processing parameters
blur_threshold: 180 # Definitely check on this - depends on camera (50 - 200)
min_width: 400
margin_fraction: 1.0 # This might need to be wider. NOTE: source of bugs!
height_output: 600 # Should be same as monitor height
width_output: 500 # Should be same as monitor width

# Margins of final output image. NOTE: highly dependent on `margin_fraction`
l: 1.5
r: 1.5
t: 2.0
b: 3.5

# Dataset parameters
face_memory: 6 # How many faces before the same is allowed again?
tolerance: 0.6 # Face recognition tolerance.

# Other parameters
triangulation_indexes: None # This should be changed to a pre-computer path.
debug_images: True
