# Camera type
camera_type: webcam #picam

# Dataset parameters
face_memory: 2 # How many faces before the same is allowed again?
tolerance: 0.6 # Face recognition tolerance.

# Image processing parameters
blur_threshold: 200 # Definitely check on this - depends on camera (50 - 200)
min_width: 150
margin_fraction: 0.6 # This might need to be wider. NOTE: source of bugs!
height_output: 1920 # Should be same as monitor height :`wlr-randr`
width_output: 1080 # Should be same as monitor width: `wlr-randr`
check_centering: False # Checks if the face is centered
check_forward: False # Checks if the face is looking forward

# Margins of final output image. NOTE: highly dependent on `margin_fraction`
l: 1.5
r: 1.5
t: 2.0
b: 2.5

# Other parameters
triangulation_indexes: None # This should be changed to a pre-computer path.
debug_images: False
